
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://otqzlvvpvlkcqlbvvngq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90cXpsdnZwdmxrY3FsYnZ2bmdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NjY4NDksImV4cCI6MjA2MDI0Mjg0OX0.JuLdaPZfGPJgM9lRqgDVetRQ3MbtXs0ldbwyEdofpQU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true
  }
});
